# Generated by Django 4.2.7 on 2026-07-04 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0003_contrato_etapa_historialetapacontrato'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_contrato', models.CharField(choices=[('RECURRENTE', 'Recurrente'), ('PERPETUO', 'Perpetuo'), ('PRO_BONO', 'Pro Bono'), ('INTERNO', 'Interno / Propio')], max_length=30)),
                ('archivo_docx', models.FileField(upload_to='plantillas_contrato/%Y/%m/')),
                ('version_codigo', models.CharField(max_length=32)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(blank=True, db_column='software_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.software')),
                ('subida_por', models.ForeignKey(blank=True, db_column='subida_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantillas_plantilladocumento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo_docx', models.FileField(editable=False, upload_to='contratos_generados/docx/%Y/%m/%d/')),
                ('archivo_pdf', models.FileField(editable=False, upload_to='contratos_generados/pdf/%Y/%m/%d/')),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('contexto_usado', models.JSONField(default=dict, editable=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='contratos.contrato')),
                ('generado_por', models.ForeignKey(blank=True, db_column='generado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(db_column='plantilla_id', on_delete=django.db.models.deletion.PROTECT, to='plantillas.plantilladocumento')),
            ],
            options={
                'db_table': 'plantillas_documentogenerado',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddIndex(
            model_name='plantilladocumento',
            index=models.Index(fields=['tipo_contrato', 'software'], name='idx_plantilla_tipo_software'),
        ),
        migrations.AddIndex(
            model_name='documentogenerado',
            index=models.Index(fields=['contrato', 'fecha_generacion'], name='idx_docgen_contrato_fecha'),
        ),
    ]
