# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clausula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("categoria", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "riesgo",
                    models.CharField(
                        choices=[
                            ("Alto", "Alto"),
                            ("Medio", "Medio"),
                            ("Bajo", "Bajo"),
                        ],
                        default="Medio",
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plantillas_clausula",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoGenerado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "archivo_docx",
                    models.FileField(
                        editable=False, upload_to="contratos_generados/docx/%Y/%m/%d/"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        editable=False, upload_to="contratos_generados/pdf/%Y/%m/%d/"
                    ),
                ),
                ("hash_sha256", models.CharField(editable=False, max_length=64)),
                ("contexto_usado", models.JSONField(default=dict, editable=False)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plantillas_documentogenerado",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="VersionClausula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("etiqueta", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Estándar", "Estándar"),
                            ("Alternativa", "Alternativa"),
                        ],
                        default="Estándar",
                        max_length=50,
                    ),
                ),
                ("texto", models.TextField()),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clausula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="plantillas.clausula",
                    ),
                ),
            ],
            options={
                "db_table": "plantillas_versionclausula",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PlantillaDocumento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("RECURRENTE", "Recurrente"),
                            ("PERPETUO", "Perpetuo"),
                            ("PRO_BONO", "Pro Bono"),
                            ("INTERNO", "Interno / Propio"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "modo_origen",
                    models.CharField(
                        choices=[
                            ("archivo", "Documento propio (.docx)"),
                            ("clausulas", "Generado por cláusulas del sistema"),
                        ],
                        default="archivo",
                        help_text="Indica si la plantilla usa un archivo .docx propio o el motor de cláusulas.",
                        max_length=20,
                    ),
                ),
                (
                    "archivo_docx",
                    models.FileField(
                        blank=True, null=True, upload_to="plantillas_contrato/%Y/%m/"
                    ),
                ),
                ("version_codigo", models.CharField(max_length=32)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clausulas_seleccionadas",
                    models.ManyToManyField(
                        blank=True, related_name="plantillas", to="plantillas.clausula"
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        blank=True,
                        db_column="software_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "db_table": "plantillas_plantilladocumento",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
