# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("plantillas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contratos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="subida_por",
            field=models.ForeignKey(
                blank=True,
                db_column="subida_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantilladocumento",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantillas",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="documentogenerado",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_generados",
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="documentogenerado",
            name="generado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="generado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentogenerado",
            name="plantilla",
            field=models.ForeignKey(
                db_column="plantilla_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="plantillas.plantilladocumento",
            ),
        ),
        migrations.AddField(
            model_name="clausula",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clausulas",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="plantilladocumento",
            index=models.Index(
                fields=["tipo_contrato", "software"], name="idx_plantilla_tipo_software"
            ),
        ),
        migrations.AddIndex(
            model_name="documentogenerado",
            index=models.Index(
                fields=["contrato", "fecha_generacion"],
                name="idx_docgen_contrato_fecha",
            ),
        ),
    ]
