# Generated by Django 4.2.7 on 2026-07-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Medio', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plantillas_clausula',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VersionClausula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Estándar', 'Estándar'), ('Alternativa', 'Alternativa')], default='Estándar', max_length=50)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='plantillas.clausula')),
            ],
            options={
                'db_table': 'plantillas_versionclausula',
                'ordering': ['id'],
            },
        ),
    ]
