# Generated by Django 4.2.7 on 2026-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_clausula_versionclausula'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausula',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='versionclausula',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
