# Generated by Django 4.2.7 on 2026-07-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="ruta_plantilla_html",
            field=models.CharField(
                blank=True,
                help_text="Ruta del archivo HTML en el backend (ej: plantillas_html/mi_plantilla.html)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plantilladocumento",
            name="modo_origen",
            field=models.CharField(
                choices=[
                    ("archivo", "Documento propio (.docx)"),
                    ("clausulas", "Generado por cláusulas del sistema"),
                    ("html", "Código HTML"),
                ],
                default="archivo",
                help_text="Indica si la plantilla usa un archivo .docx propio o el motor de cláusulas.",
                max_length=20,
            ),
        ),
    ]
