# Generated by Django 4.2.7 on 2026-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_clausula_fecha_modificacion_versionclausula_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='modo_origen',
            field=models.CharField(choices=[('archivo', 'Documento propio (.docx)'), ('clausulas', 'Generado por cláusulas del sistema')], default='archivo', help_text='Indica si la plantilla usa un archivo .docx propio o el motor de cláusulas.', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='archivo_docx',
            field=models.FileField(blank=True, null=True, upload_to='plantillas_contrato/%Y/%m/'),
        ),
    ]
