# Generated by Django 4.2.7 on 2026-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0003_plantilladocumento_ruta_plantilla_html_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clausula",
            index=models.Index(
                fields=["tenant", "activa"], name="idx_clausula_tenant_activa"
            ),
        ),
    ]
