# Generated by Django 4.2.7 on 2026-07-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_producto_datos_adicionales_producto_tipo_licencia_and_more"),
        ("plantillas", "0004_add_modo_origen_plantilladocumento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantilladocumento",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_column="software_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.producto",
            ),
        ),
    ]
