# Generated by Django 4.2.7 on 2026-07-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_backfill_membresias"),
        ("plantillas", "0004_clausula_idx_clausula_tenant_activa"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="codigo_prefijo",
            field=models.CharField(
                blank=True,
                help_text="Prefijo del correlativo de 'Referencia' para documentos HTML generados con esta plantilla (ej: NDA, MSA, TOS, REQ). El sistema arma códigos únicos tipo PREFIJO-AÑO-NNN al generar el documento; se comparte entre plantillas con el mismo prefijo (misma familia de documento) y se resetea cada año.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SecuenciaReferencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prefijo", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("ultimo_numero", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secuencias_referencia",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "plantillas_secuenciareferencia",
            },
        ),
        migrations.AddConstraint(
            model_name="secuenciareferencia",
            constraint=models.UniqueConstraint(
                fields=("tenant", "prefijo", "anio"),
                name="uniq_secuencia_tenant_prefijo_anio",
            ),
        ),
    ]
