# Generated by Django 4.2.7 on 2026-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0005_plantilladocumento_codigo_prefijo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="requiere_sla_facturacion",
            field=models.BooleanField(
                default=True,
                help_text="Si está desmarcado, el wizard 'Nuevo Contrato' no pide SLA, facturación ni días de gracia para esta plantilla (documentos administrativos como NDA, memorándums o fichas de requerimientos, que no son un servicio con nivel de servicio ni cobro). Se les asigna un SLA técnico 'N/A' automáticamente.",
            ),
        ),
    ]
