# Generated by Django 4.2.7 on 2026-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0005_alter_plantilladocumento_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="clausulas_seleccionadas",
            field=models.ManyToManyField(
                blank=True, related_name="plantillas", to="plantillas.clausula"
            ),
        ),
    ]
