# Generated by Django 4.2.7 on 2026-07-17 05:07

from django.db import migrations, models


def _backfill_confirmadas(apps, schema_editor):
    """Las plantillas anteriores a este campo ya estaban publicadas (activas o
    archivadas): se marcan confirmadas para que ninguna pase a ser eliminable."""
    PlantillaDocumento = apps.get_model("plantillas", "PlantillaDocumento")
    PlantillaDocumento.objects.update(confirmada=True)


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0007_codigo_prefijo_familia_obligatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="confirmada",
            field=models.BooleanField(
                default=False,
                help_text="False = borrador: la plantilla aún no se publicó, puede editarse y eliminarse libremente y no aparece al crear contratos. Activarla la confirma (transición de una sola vía); una plantilla confirmada ya no se elimina, solo se archiva.",
            ),
        ),
        migrations.RunPython(_backfill_confirmadas, migrations.RunPython.noop),
    ]
