# Generated by Django 4.2.7 on 2026-07-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0008_plantilladocumento_confirmada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentogenerado",
            name="plantilla",
            field=models.ForeignKey(
                db_column="plantilla_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plantillas.plantilladocumento",
            ),
        ),
    ]
