# Generated by Django 4.2.7 on 2026-07-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0009_alter_documentogenerado_plantilla"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilladocumento",
            name="portada",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de la primera página (portada) de la plantilla",
                null=True,
                upload_to="plantillas_portadas/%Y/%m/",
            ),
        ),
    ]
