# Generated by Django 4.2.7 on 2026-07-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0010_plantilladocumento_portada"),
    ]

    operations = [
        migrations.AddField(
            model_name="clausula",
            name="tipo_texto",
            field=models.CharField(
                choices=[
                    ("CLAUSULA", "Cláusula"),
                    ("SALUDO", "Saludo / Apertura"),
                    ("INTRODUCCION", "Introducción / Preámbulo"),
                    ("DESPEDIDA", "Despedida"),
                    ("CIERRE", "Cierre legal"),
                    ("FIRMA", "Bloque de firmas"),
                    ("OTRO", "Otro texto útil"),
                ],
                default="CLAUSULA",
                help_text="Función del texto dentro del documento: cláusula legal, saludo, introducción, despedida, cierre o bloque de firmas.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="clausula",
            index=models.Index(
                fields=["tenant", "tipo_texto", "activa"],
                name="idx_clausula_tenant_tipo",
            ),
        ),
    ]
