# Generated by Django 4.2.7 on 2026-07-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0011_clausula_tipo_texto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("texto", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "plantillas_opcionrespuesta",
            },
        ),
        migrations.CreateModel(
            name="PreguntaFormulario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("texto", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("booleano", "Sí / No"),
                            ("opcion_multiple", "Opción Múltiple"),
                        ],
                        default="booleano",
                        max_length=20,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "plantillas_preguntaformulario",
                "ordering": ["orden"],
            },
        ),
        migrations.AlterField(
            model_name="plantilladocumento",
            name="tipo_contrato",
            field=models.CharField(
                choices=[
                    ("RECURRENTE", "Recurrente"),
                    ("PERPETUO", "Perpetuo"),
                    ("PRO_BONO", "Pro Bono"),
                    ("INTERNO", "Interno / Propio"),
                    ("REQUERIMIENTO", "Ficha de Requerimiento"),
                    ("ERS", "Especificación de Requerimientos"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ReglaInclusionClausula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("respuesta_booleana", models.BooleanField(blank=True, null=True)),
                (
                    "clausula_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantillas.versionclausula",
                    ),
                ),
                (
                    "opcion_respuesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantillas.opcionrespuesta",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_inclusion",
                        to="plantillas.plantilladocumento",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantillas.preguntaformulario",
                    ),
                ),
            ],
            options={
                "db_table": "plantillas_reglainclusion",
            },
        ),
        migrations.AddField(
            model_name="preguntaformulario",
            name="plantilla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="plantillas.plantilladocumento",
            ),
        ),
        migrations.AddField(
            model_name="opcionrespuesta",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="plantillas.preguntaformulario",
            ),
        ),
    ]
