# Generated by Django 4.2.7 on 2026-07-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_user_cliente"),
        ("clientes", "0003_correoenviado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=150)),
                ("cuerpo", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("AVISO", "Aviso"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("leida", models.BooleanField(default=False)),
                ("leida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="creado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notificaciones_notificacion",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "leida"], name="idx_notif_cliente_leida"
                    )
                ],
            },
        ),
    ]
