# Generated by Django 4.2.7 on 2026-07-18 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_idx_cliente_tenant_active"),
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="enlace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="para_staff",
            field=models.BooleanField(
                default=False, help_text="True si es para admins/moderadores"
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="cliente_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones",
                to="clientes.cliente",
            ),
        ),
    ]
