# Generated by Django 4.2.7 on 2026-07-20 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notificaciones", "0002_notificacion_enlace_notificacion_para_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="usuario_destino",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_destino_id",
                help_text="Si está seteado, la notificación es para este usuario específico",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones_recibidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
