--
-- PostgreSQL database dump
--

\restrict e9pMaKguh21GNqDRdQc4V2DtC42AfqrqvfhiaCGNCcEengW1HtJ8ZCYVaQdw0OR

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO grivy_clm;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO grivy_clm;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO grivy_clm;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO grivy_clm;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO grivy_clm;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO grivy_clm;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalogo_software; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.catalogo_software (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    descripcion text,
    api_key uuid NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL
);


ALTER TABLE public.catalogo_software OWNER TO grivy_clm;

--
-- Name: catalogo_software_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.catalogo_software ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogo_software_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalogo_softwareversion; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.catalogo_softwareversion (
    id bigint NOT NULL,
    version_semver character varying(30) NOT NULL,
    changelog text,
    fecha_liberacion date NOT NULL,
    software_id bigint NOT NULL
);


ALTER TABLE public.catalogo_softwareversion OWNER TO grivy_clm;

--
-- Name: catalogo_softwareversion_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.catalogo_softwareversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogo_softwareversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_cliente; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.clientes_cliente (
    id integer NOT NULL,
    email_principal character varying(255) NOT NULL,
    telefono_contacto character varying(20),
    fecha_registro timestamp with time zone NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.clientes_cliente OWNER TO grivy_clm;

--
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.clientes_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_contactorepresentante; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.clientes_contactorepresentante (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    cargo character varying(100),
    email character varying(255) NOT NULL,
    telefono character varying(20),
    cliente_juridico_id integer NOT NULL
);


ALTER TABLE public.clientes_contactorepresentante OWNER TO grivy_clm;

--
-- Name: clientes_contactorepresentante_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.clientes_contactorepresentante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_contactorepresentante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_personajuridica; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.clientes_personajuridica (
    cliente_ptr_id integer NOT NULL,
    rut character varying(12) NOT NULL,
    razon_social character varying(255) NOT NULL,
    giro character varying(255)
);


ALTER TABLE public.clientes_personajuridica OWNER TO grivy_clm;

--
-- Name: clientes_personanatural; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.clientes_personanatural (
    cliente_ptr_id integer NOT NULL,
    run character varying(12) NOT NULL,
    nombre_completo character varying(255) NOT NULL
);


ALTER TABLE public.clientes_personanatural OWNER TO grivy_clm;

--
-- Name: contratos_contrato; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.contratos_contrato (
    id bigint NOT NULL,
    tipo_contrato character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    monto numeric(12,2) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_vencimiento date,
    dias_gracia_autorizados integer NOT NULL,
    fin_periodo_gracia date,
    cliente_id integer NOT NULL,
    sla_id bigint,
    software_id bigint NOT NULL,
    CONSTRAINT contratos_contrato_dias_gracia_autorizados_check CHECK ((dias_gracia_autorizados >= 0))
);


ALTER TABLE public.contratos_contrato OWNER TO grivy_clm;

--
-- Name: contratos_contrato_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.contratos_contrato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_contrato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contratos_registroperdonazo; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.contratos_registroperdonazo (
    id bigint NOT NULL,
    fecha_concesion timestamp with time zone NOT NULL,
    dias_extendidos integer NOT NULL,
    motivo text NOT NULL,
    fecha_vencimiento_anterior date NOT NULL,
    contrato_id bigint NOT NULL,
    CONSTRAINT contratos_registroperdonazo_dias_extendidos_check CHECK ((dias_extendidos >= 0))
);


ALTER TABLE public.contratos_registroperdonazo OWNER TO grivy_clm;

--
-- Name: contratos_registroperdonazo_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.contratos_registroperdonazo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_registroperdonazo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contratos_sla; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.contratos_sla (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    uptime_garantizado numeric(5,2) NOT NULL,
    tiempo_respuesta_horas integer NOT NULL,
    detalles text,
    CONSTRAINT contratos_sla_tiempo_respuesta_horas_check CHECK ((tiempo_respuesta_horas >= 0))
);


ALTER TABLE public.contratos_sla OWNER TO grivy_clm;

--
-- Name: contratos_sla_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.contratos_sla ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_sla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO grivy_clm;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO grivy_clm;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO grivy_clm;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO grivy_clm;

--
-- Name: legal_documentolegal; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.legal_documentolegal (
    id bigint NOT NULL,
    tipo character varying(20) NOT NULL,
    version_codigo character varying(20) NOT NULL,
    contenido_html text NOT NULL,
    fecha_publicacion timestamp with time zone NOT NULL,
    is_vigente boolean NOT NULL
);


ALTER TABLE public.legal_documentolegal OWNER TO grivy_clm;

--
-- Name: legal_documentolegal_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.legal_documentolegal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.legal_documentolegal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: legal_logaceptacion; Type: TABLE; Schema: public; Owner: grivy_clm
--

CREATE TABLE public.legal_logaceptacion (
    id bigint NOT NULL,
    ip_direccion inet NOT NULL,
    user_agent text NOT NULL,
    fecha_hora_registro timestamp with time zone NOT NULL,
    metadata_auditoria jsonb,
    cliente_id integer NOT NULL,
    documento_legal_id bigint NOT NULL,
    software_id bigint NOT NULL
);


ALTER TABLE public.legal_logaceptacion OWNER TO grivy_clm;

--
-- Name: legal_logaceptacion_id_seq; Type: SEQUENCE; Schema: public; Owner: grivy_clm
--

ALTER TABLE public.legal_logaceptacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.legal_logaceptacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: catalogo_software catalogo_software_api_key_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_software
    ADD CONSTRAINT catalogo_software_api_key_key UNIQUE (api_key);


--
-- Name: catalogo_software catalogo_software_nombre_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_software
    ADD CONSTRAINT catalogo_software_nombre_key UNIQUE (nombre);


--
-- Name: catalogo_software catalogo_software_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_software
    ADD CONSTRAINT catalogo_software_pkey PRIMARY KEY (id);


--
-- Name: catalogo_software catalogo_software_slug_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_software
    ADD CONSTRAINT catalogo_software_slug_key UNIQUE (slug);


--
-- Name: catalogo_softwareversion catalogo_softwareversion_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_softwareversion
    ADD CONSTRAINT catalogo_softwareversion_pkey PRIMARY KEY (id);


--
-- Name: catalogo_softwareversion catalogo_softwareversion_software_id_version_semv_5054f7cc_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_softwareversion
    ADD CONSTRAINT catalogo_softwareversion_software_id_version_semv_5054f7cc_uniq UNIQUE (software_id, version_semver);


--
-- Name: clientes_cliente clientes_cliente_email_principal_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_cliente
    ADD CONSTRAINT clientes_cliente_email_principal_key UNIQUE (email_principal);


--
-- Name: clientes_cliente clientes_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_cliente
    ADD CONSTRAINT clientes_cliente_pkey PRIMARY KEY (id);


--
-- Name: clientes_contactorepresentante clientes_contactorepresentante_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_contactorepresentante
    ADD CONSTRAINT clientes_contactorepresentante_pkey PRIMARY KEY (id);


--
-- Name: clientes_personajuridica clientes_personajuridica_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personajuridica
    ADD CONSTRAINT clientes_personajuridica_pkey PRIMARY KEY (cliente_ptr_id);


--
-- Name: clientes_personajuridica clientes_personajuridica_rut_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personajuridica
    ADD CONSTRAINT clientes_personajuridica_rut_key UNIQUE (rut);


--
-- Name: clientes_personanatural clientes_personanatural_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personanatural
    ADD CONSTRAINT clientes_personanatural_pkey PRIMARY KEY (cliente_ptr_id);


--
-- Name: clientes_personanatural clientes_personanatural_run_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personanatural
    ADD CONSTRAINT clientes_personanatural_run_key UNIQUE (run);


--
-- Name: contratos_contrato contratos_contrato_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_contrato
    ADD CONSTRAINT contratos_contrato_pkey PRIMARY KEY (id);


--
-- Name: contratos_registroperdonazo contratos_registroperdonazo_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_registroperdonazo
    ADD CONSTRAINT contratos_registroperdonazo_pkey PRIMARY KEY (id);


--
-- Name: contratos_sla contratos_sla_nombre_key; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_sla
    ADD CONSTRAINT contratos_sla_nombre_key UNIQUE (nombre);


--
-- Name: contratos_sla contratos_sla_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_sla
    ADD CONSTRAINT contratos_sla_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: legal_documentolegal legal_documentolegal_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_documentolegal
    ADD CONSTRAINT legal_documentolegal_pkey PRIMARY KEY (id);


--
-- Name: legal_documentolegal legal_documentolegal_tipo_version_codigo_d8db7f9a_uniq; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_documentolegal
    ADD CONSTRAINT legal_documentolegal_tipo_version_codigo_d8db7f9a_uniq UNIQUE (tipo, version_codigo);


--
-- Name: legal_logaceptacion legal_logaceptacion_pkey; Type: CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_logaceptacion
    ADD CONSTRAINT legal_logaceptacion_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: catalogo_software_nombre_6e231754_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX catalogo_software_nombre_6e231754_like ON public.catalogo_software USING btree (nombre varchar_pattern_ops);


--
-- Name: catalogo_software_slug_a78003ac_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX catalogo_software_slug_a78003ac_like ON public.catalogo_software USING btree (slug varchar_pattern_ops);


--
-- Name: catalogo_softwareversion_software_id_9e585922; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX catalogo_softwareversion_software_id_9e585922 ON public.catalogo_softwareversion USING btree (software_id);


--
-- Name: clientes_cliente_email_principal_3fe6d889_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX clientes_cliente_email_principal_3fe6d889_like ON public.clientes_cliente USING btree (email_principal varchar_pattern_ops);


--
-- Name: clientes_contactorepresentante_cliente_juridico_id_12547828; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX clientes_contactorepresentante_cliente_juridico_id_12547828 ON public.clientes_contactorepresentante USING btree (cliente_juridico_id);


--
-- Name: clientes_personajuridica_rut_c865220e_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX clientes_personajuridica_rut_c865220e_like ON public.clientes_personajuridica USING btree (rut varchar_pattern_ops);


--
-- Name: clientes_personanatural_run_35dbc1a0_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX clientes_personanatural_run_35dbc1a0_like ON public.clientes_personanatural USING btree (run varchar_pattern_ops);


--
-- Name: contratos_contrato_cliente_id_1993b39b; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX contratos_contrato_cliente_id_1993b39b ON public.contratos_contrato USING btree (cliente_id);


--
-- Name: contratos_contrato_sla_id_3cf7caae; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX contratos_contrato_sla_id_3cf7caae ON public.contratos_contrato USING btree (sla_id);


--
-- Name: contratos_contrato_software_id_8298ecd8; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX contratos_contrato_software_id_8298ecd8 ON public.contratos_contrato USING btree (software_id);


--
-- Name: contratos_registroperdonazo_contrato_id_78aa66a5; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX contratos_registroperdonazo_contrato_id_78aa66a5 ON public.contratos_registroperdonazo USING btree (contrato_id);


--
-- Name: contratos_sla_nombre_6d9befec_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX contratos_sla_nombre_6d9befec_like ON public.contratos_sla USING btree (nombre varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: legal_logaceptacion_cliente_id_bffadbc8; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX legal_logaceptacion_cliente_id_bffadbc8 ON public.legal_logaceptacion USING btree (cliente_id);


--
-- Name: legal_logaceptacion_documento_legal_id_04fd096f; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX legal_logaceptacion_documento_legal_id_04fd096f ON public.legal_logaceptacion USING btree (documento_legal_id);


--
-- Name: legal_logaceptacion_software_id_25b025df; Type: INDEX; Schema: public; Owner: grivy_clm
--

CREATE INDEX legal_logaceptacion_software_id_25b025df ON public.legal_logaceptacion USING btree (software_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalogo_softwareversion catalogo_softwarever_software_id_9e585922_fk_catalogo_; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.catalogo_softwareversion
    ADD CONSTRAINT catalogo_softwarever_software_id_9e585922_fk_catalogo_ FOREIGN KEY (software_id) REFERENCES public.catalogo_software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_contactorepresentante clientes_contactorep_cliente_juridico_id_12547828_fk_clientes_; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_contactorepresentante
    ADD CONSTRAINT clientes_contactorep_cliente_juridico_id_12547828_fk_clientes_ FOREIGN KEY (cliente_juridico_id) REFERENCES public.clientes_personajuridica(cliente_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_personajuridica clientes_personajuri_cliente_ptr_id_13a2a86a_fk_clientes_; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personajuridica
    ADD CONSTRAINT clientes_personajuri_cliente_ptr_id_13a2a86a_fk_clientes_ FOREIGN KEY (cliente_ptr_id) REFERENCES public.clientes_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_personanatural clientes_personanatu_cliente_ptr_id_fddecc57_fk_clientes_; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.clientes_personanatural
    ADD CONSTRAINT clientes_personanatu_cliente_ptr_id_fddecc57_fk_clientes_ FOREIGN KEY (cliente_ptr_id) REFERENCES public.clientes_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contratos_contrato contratos_contrato_cliente_id_1993b39b_fk_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_contrato
    ADD CONSTRAINT contratos_contrato_cliente_id_1993b39b_fk_clientes_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.clientes_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contratos_contrato contratos_contrato_sla_id_3cf7caae_fk_contratos_sla_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_contrato
    ADD CONSTRAINT contratos_contrato_sla_id_3cf7caae_fk_contratos_sla_id FOREIGN KEY (sla_id) REFERENCES public.contratos_sla(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contratos_contrato contratos_contrato_software_id_8298ecd8_fk_catalogo_software_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_contrato
    ADD CONSTRAINT contratos_contrato_software_id_8298ecd8_fk_catalogo_software_id FOREIGN KEY (software_id) REFERENCES public.catalogo_software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contratos_registroperdonazo contratos_registrope_contrato_id_78aa66a5_fk_contratos; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.contratos_registroperdonazo
    ADD CONSTRAINT contratos_registrope_contrato_id_78aa66a5_fk_contratos FOREIGN KEY (contrato_id) REFERENCES public.contratos_contrato(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: legal_logaceptacion legal_logaceptacion_cliente_id_bffadbc8_fk_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_logaceptacion
    ADD CONSTRAINT legal_logaceptacion_cliente_id_bffadbc8_fk_clientes_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.clientes_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: legal_logaceptacion legal_logaceptacion_documento_legal_id_04fd096f_fk_legal_doc; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_logaceptacion
    ADD CONSTRAINT legal_logaceptacion_documento_legal_id_04fd096f_fk_legal_doc FOREIGN KEY (documento_legal_id) REFERENCES public.legal_documentolegal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: legal_logaceptacion legal_logaceptacion_software_id_25b025df_fk_catalogo_; Type: FK CONSTRAINT; Schema: public; Owner: grivy_clm
--

ALTER TABLE ONLY public.legal_logaceptacion
    ADD CONSTRAINT legal_logaceptacion_software_id_25b025df_fk_catalogo_ FOREIGN KEY (software_id) REFERENCES public.catalogo_software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON SCHEMA public TO grivy_clm;


--
-- PostgreSQL database dump complete
--

\unrestrict e9pMaKguh21GNqDRdQc4V2DtC42AfqrqvfhiaCGNCcEengW1HtJ8ZCYVaQdw0OR

