# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Bot", "Bot"),
                            ("Agente", "Agente"),
                            ("Script", "Script"),
                            ("Software", "Software"),
                            ("Auditoría", "Auditoría"),
                            ("Consultoría", "Consultoría"),
                        ],
                        default="Software",
                        max_length=20,
                    ),
                ),
                ("tipo_licencia", models.CharField(default="Comercial", max_length=30)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("moneda", models.CharField(default="USD", max_length=8)),
                ("unidad", models.CharField(blank=True, default="", max_length=40)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Descontinuado", "Descontinuado"),
                        ],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                ("datos_adicionales", models.JSONField(blank=True, default=dict)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "catalogo_producto",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "api_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "catalogo_software",
            },
        ),
        migrations.CreateModel(
            name="SoftwareVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_semver", models.CharField(max_length=32)),
                ("changelog", models.TextField(blank=True, null=True)),
                ("fecha_liberacion", models.DateField()),
                (
                    "software",
                    models.ForeignKey(
                        db_column="software_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalogo.software",
                    ),
                ),
            ],
            options={
                "db_table": "catalogo_softwareversion",
            },
        ),
    ]
