# Generated by Django 4.2.7 on 2026-07-02 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogo_software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_semver', models.CharField(max_length=32)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('fecha_liberacion', models.DateField()),
                ('software', models.ForeignKey(db_column='software_id', on_delete=django.db.models.deletion.RESTRICT, to='catalogo.software')),
            ],
            options={
                'db_table': 'catalogo_softwareversion',
            },
        ),
    ]
