# Generated by Django 4.2.7 on 2026-07-02 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_semver', models.CharField(max_length=30)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('fecha_liberacion', models.DateField(default=django.utils.timezone.now)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='catalogo.software')),
            ],
            options={
                'ordering': ['-fecha_liberacion'],
                'unique_together': {('software', 'version_semver')},
            },
        ),
    ]
