# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="softwares",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="tenants.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="software",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nombre"), name="uniq_software_nombre_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="software",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="uniq_software_slug_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="uniq_producto_sku_por_tenant"
            ),
        ),
    ]
