# Generated by Django 4.2.7 on 2026-07-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('Software', 'Software'), ('Servicio', 'Servicio'), ('Soporte', 'Soporte'), ('Formación', 'Formación')], default='Software', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=8)),
                ('unidad', models.CharField(blank=True, default='', max_length=40)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Descontinuado', 'Descontinuado')], default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogo_producto',
                'ordering': ['nombre'],
            },
        ),
    ]
