# Generated by Django 4.2.7 on 2026-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["tenant", "estado"], name="idx_producto_tenant_estado"
            ),
        ),
    ]
