# Generated by Django 4.2.7 on 2026-07-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_licencia',
            field=models.CharField(default='Comercial', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Bot', 'Bot'), ('Agente', 'Agente'), ('Script', 'Script'), ('Software', 'Software'), ('Auditoría', 'Auditoría'), ('Consultoría', 'Consultoría')], default='Software', max_length=20),
        ),
    ]
