# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoLegal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=30)),
                ("version_codigo", models.CharField(max_length=32)),
                ("contenido_html", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("is_vigente", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "legal_documentolegal",
            },
        ),
        migrations.CreateModel(
            name="LogAceptacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ip_direccion", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("fecha_hora_registro", models.DateTimeField(auto_now_add=True)),
                ("metadata_auditoria", models.JSONField(default=dict)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "documento_legal",
                    models.ForeignKey(
                        db_column="documento_legal_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="legal.documentolegal",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        db_column="software_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "db_table": "legal_logaceptacion",
            },
        ),
    ]
