# Generated by Django 4.2.7 on 2026-07-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TYC', 'Términos y Condiciones'), ('PRIVACIDAD', 'Privacidad')], max_length=20)),
                ('version_codigo', models.CharField(max_length=20)),
                ('contenido_html', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('is_vigente', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('tipo', 'version_codigo')},
            },
        ),
        migrations.CreateModel(
            name='LogAceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_direccion', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('metadata_auditoria', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_legales', to='clientes.cliente')),
                ('documento_legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.documentolegal')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.software')),
            ],
        ),
    ]
