# Generated by Django 4.2.7 on 2026-07-09 03:40

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentolegal",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_legales",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="logaceptacion",
            index=models.Index(
                fields=["cliente", "documento_legal"], name="idx_log_cliente_doc"
            ),
        ),
        migrations.AddIndex(
            model_name="logaceptacion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata_auditoria"], name="idx_log_metadata_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegal",
            index=models.Index(
                condition=models.Q(("is_vigente", True)),
                fields=["id"],
                name="idx_doc_legal_vigente",
            ),
        ),
    ]
