# Generated by Django 4.2.7 on 2026-07-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Modificar la tabla para que sea particionada (si no se hizo mediante el create inicial)
            -- Nota: PostgreSQL requiere que las tablas particionadas se definan como tales desde su creación.
            CREATE TABLE legal_logaceptacion_partitioned (
                id bigint GENERATED ALWAYS AS IDENTITY,
                cliente_id bigint NOT NULL,
                software_id bigint NOT NULL,
                documento_legal_id bigint NOT NULL,
                ip_direccion inet NOT NULL,
                user_agent text NOT NULL,
                fecha_hora_registro timestamptz NOT NULL DEFAULT NOW(),
                metadata_auditoria jsonb NOT NULL DEFAULT '{}'::jsonb,
                PRIMARY KEY (id, fecha_hora_registro)
            ) PARTITION BY RANGE (fecha_hora_registro);
            
            -- Crear la primera partición para producción
            CREATE TABLE legal_logaceptacion_y2026 PARTITION OF legal_logaceptacion_partitioned
                FOR VALUES FROM ('2026-01-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');
            """,
            reverse_sql="DROP TABLE legal_logaceptacion_partitioned;"
        ),
    ]
