# Generated by Django 4.2.7 on 2026-07-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_producto_datos_adicionales_producto_tipo_licencia_and_more"),
        ("legal", "0002_auto_20260703_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logaceptacion",
            name="software",
            field=models.ForeignKey(
                db_column="software_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.producto",
            ),
        ),
    ]
