# Generated by Django 4.2.7 on 2026-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentolegal",
            name="idx_doc_legal_vigente",
        ),
        migrations.AddIndex(
            model_name="documentolegal",
            index=models.Index(
                condition=models.Q(("is_vigente", True)),
                fields=["tenant", "tipo"],
                name="idx_doc_legal_vigente",
            ),
        ),
    ]
