# Generated by Django 4.2.7 on 2026-07-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0006_contrato_nombre"),
        ("legal", "0003_remove_documentolegal_idx_doc_legal_vigente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisContratoIA",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_analisis", models.DateTimeField(auto_now_add=True)),
                ("checklist_cumplido", models.BooleanField(default=False)),
                ("resultado_checklist_json", models.JSONField(default=dict)),
                ("riesgos_detectados_json", models.JSONField(default=list)),
                ("texto_analizado", models.TextField(blank=True, null=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_ia",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "db_table": "legal_analisiscontratoia",
                "ordering": ["-fecha_analisis"],
            },
        ),
    ]
