# Generated by Django 4.2.7 on 2026-07-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente_id_origen",
                    models.IntegerField(
                        help_text="ID original del cliente en la BD transaccional",
                        unique=True,
                    ),
                ),
                ("tipo_cliente", models.CharField(max_length=50)),
                ("nombre_completo", models.CharField(max_length=255)),
                (
                    "rut_identificador",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                ("industria", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dimensión Cliente",
                "verbose_name_plural": "Dimensiones Cliente",
                "db_table": "dwh_dim_cliente",
            },
        ),
        migrations.CreateModel(
            name="DimSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "software_id_origen",
                    models.IntegerField(
                        help_text="ID original del software", unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Dimensión Software",
                "verbose_name_plural": "Dimensiones Software",
                "db_table": "dwh_dim_software",
            },
        ),
        migrations.CreateModel(
            name="FactContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contrato_id_origen",
                    models.IntegerField(
                        help_text="ID original del contrato", unique=True
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("etapa", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_termino", models.DateField(blank=True, null=True)),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ingreso_mensual_recurrente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="MRR calculado",
                        max_digits=12,
                    ),
                ),
                (
                    "sla_cumplimiento_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dim_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimcliente",
                    ),
                ),
                (
                    "dim_software",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimsoftware",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hecho Contrato",
                "verbose_name_plural": "Hechos Contrato",
                "db_table": "dwh_fact_contrato",
            },
        ),
    ]
