# Generated by Django 4.2.7 on 2026-07-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_initial"),
        ("tenants", "0003_user_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_documento",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "documentos_tipodocumento",
                "unique_together": {("tenant", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="RequisitoDocumental",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("TODOS", "Aplica a todos"),
                            ("NATURAL", "Solo Persona Natural"),
                            ("JURIDICA", "Solo Persona Jurídica"),
                        ],
                        default="TODOS",
                        max_length=20,
                    ),
                ),
                (
                    "categoria_producto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bot", "Bot"),
                            ("Agente", "Agente"),
                            ("Script", "Script"),
                            ("Software", "Software"),
                            ("Auditoría", "Auditoría"),
                            ("Consultoría", "Consultoría"),
                        ],
                        help_text="Ej: 'Software', 'Bot'. Si está vacío, no filtra por categoría.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("es_obligatorio", models.BooleanField(default=True)),
                (
                    "producto_especifico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aplica solo a este producto específico.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.producto",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos_documentales",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos",
                        to="documentos.tipodocumento",
                    ),
                ),
            ],
            options={
                "db_table": "documentos_requisitodocumental",
            },
        ),
    ]
