# Generated by Django 4.2.7 on 2026-07-09 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="platform_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPERADMIN", "Super Administrador"),
                    ("MODERADOR", "Moderador"),
                    ("TRABAJADOR", "Trabajador"),
                ],
                help_text="Solo aplica cuando tenant es null (staff de la plataforma).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("TENANT_ADMIN", "Administrador de Cuenta"),
                    ("OPERADOR", "Operador"),
                    ("AUDITOR", "Auditor Legal"),
                    ("CLIENTE", "Cliente Externo"),
                ],
                default="OPERADOR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClienteGrant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants_trabajador",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "otorgado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        limit_choices_to={"platform_role": "TRABAJADOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_concedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_clientegrant",
            },
        ),
        migrations.AddConstraint(
            model_name="clientegrant",
            constraint=models.UniqueConstraint(
                fields=("trabajador", "cliente"), name="uniq_trabajador_cliente"
            ),
        ),
    ]
