# Generated by Django 4.2.7 on 2026-07-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
        ("tenants", "0002_user_platform_role_alter_user_role_clientegrant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="cliente_id",
                help_text="Solo aplica cuando role=CLIENTE: el Cliente al que pertenece este usuario externo, usado para scoping de incidencias/contratos.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_cuenta",
                to="clientes.cliente",
            ),
        ),
    ]
