# Generated by Django 4.2.7 on 2026-07-13 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_user_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("SIN_MEMBRESIA", "Sin Membresía"),
                    ("COBRE", "Cobre"),
                    ("PLATA", "Plata"),
                    ("PLATINO", "Platino"),
                    ("DIAMANTE", "Diamante"),
                    ("OBSIDIANA", "Obsidiana"),
                ],
                default="SIN_MEMBRESIA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("SIN_MEMBRESIA", "Sin Membresía"),
                            ("COBRE", "Cobre"),
                            ("PLATA", "Plata"),
                            ("PLATINO", "Platino"),
                            ("DIAMANTE", "Diamante"),
                            ("OBSIDIANA", "Obsidiana"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("EXPIRADA", "Expirada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True, help_text="Vacío = indefinida.", null=True
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "otorgada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_membresia",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ACTIVA")),
                fields=("tenant",),
                name="uniq_membresia_activa_por_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.CheckConstraint(
                check=models.Q(("categoria", "SIN_MEMBRESIA"), _negated=True),
                name="membresia_categoria_de_pago",
            ),
        ),
    ]
