"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$+=zhl#u$2u5no#cvk+15)#%p)$r3k^0yh8d0)5z*$j1^=nanq'

# SECURITY WARNING: don't run with debug turned on in production!
# Default False (seguro) — se activa solo si .env trae DEBUG=True.
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['144.217.10.38', 'localhost', '127.0.0.1']

# Metadatos de auditoría inyectados en documentos exportados (ver documentos/services/exportar.py)
APP_NAME = 'Enfoque Platform'
APP_VERSION = '1.0.4'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'clientes',
    'catalogo',
    'contratos',
    'legal',
    'documentos',
    'plantillas',
    'axes',
    'django_otp',
    'django_otp.plugins.otp_totp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SoftwareIsolationMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tu_base_de_datos'),
        'USER': os.environ.get('DB_USER', 'tu_usuario'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'tu_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Archivos subidos por los usuarios / Documentos de proyectos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Motor de plantillas (ver app 'plantillas'): binario de LibreOffice usado para
# convertir el .docx renderizado a PDF, y límite de tamaño para plantillas subidas.
LIBREOFFICE_BINARY = os.environ.get('LIBREOFFICE_BINARY', 'soffice')
PLANTILLAS_MAX_UPLOAD_MB = int(os.environ.get('PLANTILLAS_MAX_UPLOAD_MB', 10))

# ==========================================
# CONFIGURACIONES DE SEGURIDAD GRADO MILITAR
# ==========================================

# 1. Backends de autenticación (Soporte para Axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# 2. Configuración de Django Axes (Bloqueo de fuerza bruta)
AXES_FAILURE_LIMIT = 3 # Bloquear tras 3 intentos fallidos
AXES_COOLOFF_TIME = 1 # Tiempo de bloqueo en horas
AXES_RESET_ON_SUCCESS = True # Resetear contadores al loguearse con éxito
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]] # Bloquear por combinación de usuario e IP

# 3. Seguridad de Sesiones y Cookies
# NOTA: En producción (HTTPS) cambiar SESSION_COOKIE_SECURE y CSRF_COOKIE_SECURE a True
SESSION_COOKIE_SECURE = False      # False para desarrollo HTTP local
CSRF_COOKIE_SECURE = False         # False para desarrollo HTTP local
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'   # Lax permite cookies desde el frontend Vite en dev
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 900           # 15 minutos de inactividad

# ==========================================
# DJANGO REST FRAMEWORK
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ==========================================
# CORS (para el frontend Vite en desarrollo)
# ==========================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
    'http://144.217.10.38:5173',
]
