"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY no está definido. Agrégalo al archivo .env (nunca lo hardcodees ni lo comitees).'
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Default False (seguro) — se activa solo si .env trae DEBUG=True.
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['144.217.10.38', 'clm.grivyzom.com', 'localhost', '127.0.0.1']

# Metadatos de auditoría inyectados en documentos exportados (ver documentos/services/exportar.py)
APP_NAME = 'Enfoque Platform'
APP_VERSION = '1.0.4'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tenants',
    'core',
    'clientes',
    'catalogo',
    'contratos',
    'legal',
    'documentos',
    'plantillas',
    'requerimientos',
    'analytics',
    'incidencias',
    'notificaciones',
    'axes',
    'django_otp',
    'django_otp.plugins.otp_totp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'core.middleware.ClienteBloqueadoMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SoftwareIsolationMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Multi-tenant: usuario custom con FK a Tenant (tenants/models.py).
# tenant=None ⇒ staff global de la plataforma (superadmin).
AUTH_USER_MODEL = 'tenants.User'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tu_base_de_datos'),
        'USER': os.environ.get('DB_USER', 'tu_usuario'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'tu_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # Sin esto, Django abre/cierra una conexión TCP+auth por request.
        # 60s reutiliza la conexión entre requests (impacto crece con tráfico/tenants);
        # CONN_HEALTH_CHECKS evita servir una conexión muerta tras ese período.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 60)),
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Archivos subidos por los usuarios / Documentos de proyectos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage de archivos (docx/pdf generados, adjuntos, firmas): filesystem local
# por default (como siempre). USE_S3_STORAGE=true lo cambia a S3 sin tocar
# código de las apps (todas usan FileField / storage.url(), no rutas de disco
# a mano) — requiere django-storages + boto3 instalados y las credenciales de
# abajo. Sin la env var, este bloque no se ejecuta y nada cambia.
USE_S3_STORAGE = os.environ.get('USE_S3_STORAGE', 'false').lower() == 'true'

if USE_S3_STORAGE:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': os.environ['AWS_STORAGE_BUCKET_NAME'],
                'region_name': os.environ.get('AWS_S3_REGION_NAME', 'us-east-1'),
                'access_key': os.environ.get('AWS_ACCESS_KEY_ID'),
                'secret_key': os.environ.get('AWS_SECRET_ACCESS_KEY'),
                'default_acl': None,  # el bucket controla acceso vía policy, no ACLs por objeto
                'file_overwrite': False,
                'querystring_auth': True,  # URLs firmadas y temporales (documentos con datos de clientes)
                'querystring_expire': 3600,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Motor de plantillas (ver app 'plantillas'): binario de LibreOffice usado para
# convertir el .docx renderizado a PDF, y límite de tamaño para plantillas subidas.
LIBREOFFICE_BINARY = os.environ.get('LIBREOFFICE_BINARY', 'soffice')
PLANTILLAS_MAX_UPLOAD_MB = int(os.environ.get('PLANTILLAS_MAX_UPLOAD_MB', 10))

# Carpeta donde el equipo deja plantillas HTML de documentos (formato .dc.html
# exportado desde Claude Design). El motor las adapta a página imprimible y
# genera el PDF con WeasyPrint respetando el diseño original.
DOCS_TEMPLATE_DIR = Path(os.environ.get(
    'DOCS_TEMPLATE_DIR',
    BASE_DIR.parent / 'clm_frontend' / 'public' / 'docs_template',
))

# Adjuntos de incidencias (capturas/logs, ver app 'incidencias')
INCIDENCIAS_MAX_UPLOAD_MB = int(os.environ.get('INCIDENCIAS_MAX_UPLOAD_MB', 10))

# ==========================================
# CONFIGURACIONES DE SEGURIDAD GRADO MILITAR
# ==========================================

# 1. Backends de autenticación (Soporte para Axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# 2. Configuración de Django Axes (Bloqueo de fuerza bruta)
AXES_FAILURE_LIMIT = 3 # Bloquear tras 3 intentos fallidos
AXES_COOLOFF_TIME = 1 # Tiempo de bloqueo en horas
AXES_RESET_ON_SUCCESS = True # Resetear contadores al loguearse con éxito
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]] # Bloquear por combinación de usuario e IP

# 3. Seguridad de Sesiones y Cookies
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'   # Lax permite cookies desde el frontend Vite en dev
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 900           # 15 minutos de inactividad

# 4. Cabeceras de Seguridad del Servidor (SecurityMiddleware)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'           # Previene Clickjacking
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Reconocer cabecera de proxy inverso para conexiones HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ==========================================
# DJANGO REST FRAMEWORK
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '300/min',
        'anon': '60/min',
    },
}

# ==========================================
# CORS (para el frontend Vite en desarrollo)
# ==========================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
    'http://144.217.10.38',
    'https://144.217.10.38',
    'http://clm.grivyzom.com',
    'https://clm.grivyzom.com',
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
    'http://144.217.10.38:5173',
    'http://144.217.10.38',
    'https://144.217.10.38',
    'http://clm.grivyzom.com',
    'https://clm.grivyzom.com',
]

# ==========================================
# EMAIL CONFIGURATION (Hostinger)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'no-reply@grivyzom.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'Enfoque Platform <no-reply@grivyzom.com>'

# Base para los enlaces que van en correos (reset de contraseña, etc.).
# Nunca derivar del Host header de la request (host header injection).
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'https://clm.grivyzom.com')

# Vigencia del magic-link de firma electrónica OTP (ver contratos.TokenFirmaContrato).
FIRMA_TOKEN_EXPIRATION_DAYS = int(os.environ.get('FIRMA_TOKEN_EXPIRATION_DAYS', 7))

# Tiempo mínimo entre dos envíos de correo de firma para el mismo contrato
# (evita que reenviar o regenerar el documento en loop spamee el correo del
# cliente con enlaces de firma).
FIRMA_REENVIO_COOLDOWN_SEGUNDOS = int(os.environ.get('FIRMA_REENVIO_COOLDOWN_SEGUNDOS', 60))
