# Generated by Django 4.2.7 on 2026-07-11 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_initial"),
        ("contratos", "0002_initial"),
        ("tenants", "0002_user_platform_role_alter_user_role_clientegrant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_PROGRESO", "En progreso"),
                            ("RESUELTO", "Resuelto"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ABIERTO",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        db_column="asignado_a_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_column="contrato_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="reportado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_reportadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        blank=True,
                        db_column="software_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "incidencias_incidencia",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoIncidencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_PROGRESO", "En progreso"),
                            ("RESUELTO", "Resuelto"),
                            ("CERRADO", "Cerrado"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_PROGRESO", "En progreso"),
                            ("RESUELTO", "Resuelto"),
                            ("CERRADO", "Cerrado"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                (
                    "incidencia",
                    models.ForeignKey(
                        db_column="incidencia_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="incidencias.incidencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incidencias_historialestado",
                "ordering": ["fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioIncidencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mensaje", models.TextField()),
                (
                    "es_interno",
                    models.BooleanField(
                        default=False,
                        help_text="Nota interna de staff, nunca visible para el cliente externo.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        db_column="autor_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incidencia",
                    models.ForeignKey(
                        db_column="incidencia_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="incidencias.incidencia",
                    ),
                ),
            ],
            options={
                "db_table": "incidencias_comentario",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="AdjuntoIncidencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("archivo", models.FileField(upload_to="incidencias/%Y/%m/%d/")),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        blank=True,
                        db_column="comentario_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="incidencias.comentarioincidencia",
                    ),
                ),
                (
                    "incidencia",
                    models.ForeignKey(
                        db_column="incidencia_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="incidencias.incidencia",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="subido_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incidencias_adjunto",
            },
        ),
        migrations.AddIndex(
            model_name="incidencia",
            index=models.Index(
                fields=["tenant", "estado"], name="idx_incidencia_tenant_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="incidencia",
            index=models.Index(
                fields=["cliente", "estado"], name="idx_incidencia_cliente_estado"
            ),
        ),
    ]
