# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email_principal", models.CharField(max_length=255)),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "clientes_cliente",
            },
        ),
        migrations.CreateModel(
            name="ContactoRepresentante",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("cargo", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "clientes_contactorepresentante",
            },
        ),
        migrations.CreateModel(
            name="PersonaJuridica",
            fields=[
                (
                    "cliente_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="clientes.cliente",
                    ),
                ),
                ("rut", models.CharField(max_length=12)),
                ("razon_social", models.CharField(max_length=255)),
                ("giro", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "clientes_personajuridica",
            },
            bases=("clientes.cliente",),
        ),
        migrations.CreateModel(
            name="PersonaNatural",
            fields=[
                (
                    "cliente_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="clientes.cliente",
                    ),
                ),
                ("run", models.CharField(max_length=12)),
                ("nombre_completo", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "clientes_personanatural",
            },
            bases=("clientes.cliente",),
        ),
    ]
