# Generated by Django 4.2.7 on 2026-07-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_principal', models.EmailField(max_length=255, unique=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Persona Jurídica',
                'verbose_name_plural': 'Personas Jurídicas',
            },
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
            },
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='ContactoRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_juridico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.personajuridica')),
            ],
        ),
    ]
