# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="contactorepresentante",
            name="cliente_juridico",
            field=models.ForeignKey(
                db_column="cliente_juridico_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.personajuridica",
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                fields=("tenant", "email_principal"),
                name="uniq_cliente_email_por_tenant",
            ),
        ),
    ]
