# Generated by Django 4.2.7 on 2026-07-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_user_cliente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorreoEnviado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("destinatario", models.EmailField(max_length=255)),
                ("asunto", models.CharField(max_length=200)),
                ("cuerpo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ENVIADO", "Enviado"), ("FALLIDO", "Fallido")],
                        default="ENVIADO",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="enviado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correos_cliente_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos_enviados",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clientes_correoenviado",
                "ordering": ["-fecha_envio"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "fecha_envio"],
                        name="idx_correo_cliente_fecha",
                    )
                ],
            },
        ),
    ]
