# Generated by Django 4.2.7 on 2026-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_correoenviado"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_cliente_tenant_active"
            ),
        ),
    ]
