# Generated by Django 4.2.7 on 2026-07-13 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0005_backfill_membresias"),
        ("contratos", "0002_initial"),
        ("clientes", "0003_correoenviado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaRequerimiento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "categoria_producto",
                    models.CharField(
                        choices=[
                            ("Bot", "Bot"),
                            ("Agente", "Agente"),
                            ("Script", "Script"),
                            ("Software", "Software"),
                            ("Auditoría", "Auditoría"),
                            ("Consultoría", "Consultoría"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("activa", models.BooleanField(default=True)),
                (
                    "secciones",
                    models.JSONField(
                        default=list,
                        help_text='Lista de secciones: [{"titulo": "...", "preguntas": [{"id": "slug", "texto": "...", "tipo": "texto|parrafo|numero|booleano|seleccion|fecha", "opciones": ["..."], "requerida": true}]}]',
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_requerimiento",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "requerimientos_plantillarequerimiento",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Requerimiento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "categoria_producto",
                    models.CharField(
                        choices=[
                            ("Bot", "Bot"),
                            ("Agente", "Agente"),
                            ("Script", "Script"),
                            ("Software", "Software"),
                            ("Auditoría", "Auditoría"),
                            ("Consultoría", "Consultoría"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "respuestas",
                    models.JSONField(
                        blank=True, default=dict, help_text="{pregunta_id: valor}"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("BORRADOR", "Borrador"), ("GENERADO", "Generado")],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_generacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimientos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_column="contrato_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimientos",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="creado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        db_column="plantilla_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requerimientos.plantillarequerimiento",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requerimientos",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "requerimientos_requerimiento",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="RequerimientoGenerado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "archivo_docx",
                    models.FileField(
                        editable=False,
                        upload_to="requerimientos_generados/docx/%Y/%m/%d/",
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        editable=False,
                        upload_to="requerimientos_generados/pdf/%Y/%m/%d/",
                    ),
                ),
                ("hash_sha256", models.CharField(editable=False, max_length=64)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="generado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requerimiento",
                    models.ForeignKey(
                        db_column="requerimiento_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_generados",
                        to="requerimientos.requerimiento",
                    ),
                ),
            ],
            options={
                "db_table": "requerimientos_requerimientogenerado",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["requerimiento", "fecha_generacion"],
                        name="idx_reqgen_requerimiento_fecha",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="requerimiento",
            index=models.Index(
                fields=["cliente", "estado"], name="idx_requerim_cliente_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="requerimiento",
            index=models.Index(
                fields=["tenant", "estado"], name="idx_requerim_tenant_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="plantillarequerimiento",
            index=models.Index(
                fields=["categoria_producto", "activa"],
                name="idx_plantreq_categoria_activa",
            ),
        ),
    ]
