# Generated by Django 4.2.7 on 2026-07-02 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('RECURRENTE', 'Recurrente'), ('PERPETUO', 'Perpetuo'), ('PRO_BONO', 'Pro-bono')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('MORA', 'Mora'), ('GRACIA', 'Gracia'), ('SUSPENDIDO', 'Suspendido'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('dias_gracia_autorizados', models.PositiveIntegerField(default=0)),
                ('fin_periodo_gracia', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('uptime_garantizado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_respuesta_horas', models.PositiveIntegerField()),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPerdonazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_concesion', models.DateTimeField(auto_now_add=True)),
                ('dias_extendidos', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('fecha_vencimiento_anterior', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdonazos', to='contratos.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.sla'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.software'),
        ),
    ]
