# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("archivo", models.FileField(upload_to="archivos_proyectos/%Y/%m/%d/")),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contratos_archivoadjunto",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador (Draft)"),
                            ("REVISION", "En Revisión / Negociación"),
                            ("APROBADO", "Aprobado internamente"),
                            ("PENDIENTE_FIRMA", "Pendiente de Firma"),
                            ("ACTIVO", "Activo / Ejecutado"),
                            ("ENMENDADO", "Enmendado (Amended)"),
                            ("TERMINADO", "Terminado / Expirado"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("RECURRENTE", "Recurrente"),
                            ("PERPETUO", "Perpetuo"),
                            ("PRO_BONO", "Pro Bono"),
                            ("INTERNO", "Interno / Propio"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("MORA", "Mora"),
                            ("GRACIA", "Gracia"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="ACTIVO",
                        max_length=30,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                (
                    "frecuencia_facturacion",
                    models.CharField(
                        blank=True,
                        choices=[("MENSUAL", "Mensual"), ("ANUAL", "Anual")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("dias_gracia_autorizados", models.IntegerField(default=0)),
                ("fin_periodo_gracia", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "texto_adicional_clausulas",
                    models.TextField(
                        blank=True,
                        help_text="Texto editable para contratos generados por cláusulas",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "contratos_contrato",
            },
        ),
        migrations.CreateModel(
            name="HistorialEtapaContrato",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "etapa_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BORRADOR", "Borrador (Draft)"),
                            ("REVISION", "En Revisión / Negociación"),
                            ("APROBADO", "Aprobado internamente"),
                            ("PENDIENTE_FIRMA", "Pendiente de Firma"),
                            ("ACTIVO", "Activo / Ejecutado"),
                            ("ENMENDADO", "Enmendado (Amended)"),
                            ("TERMINADO", "Terminado / Expirado"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "etapa_nueva",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador (Draft)"),
                            ("REVISION", "En Revisión / Negociación"),
                            ("APROBADO", "Aprobado internamente"),
                            ("PENDIENTE_FIRMA", "Pendiente de Firma"),
                            ("ACTIVO", "Activo / Ejecutado"),
                            ("ENMENDADO", "Enmendado (Amended)"),
                            ("TERMINADO", "Terminado / Expirado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "contratos_historialetapa",
            },
        ),
        migrations.CreateModel(
            name="ObligacionSLA",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipo_obligacion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("penalizacion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contratos_obligacion_sla",
            },
        ),
        migrations.CreateModel(
            name="ObligacionSLAAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("obligacion_id", models.IntegerField(blank=True, null=True)),
                ("tipo_obligacion", models.CharField(max_length=100)),
                ("actor_nombre", models.CharField(default="Sistema", max_length=150)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("accion", models.CharField(max_length=10)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "contratos_obligacionsla_auditlog",
            },
        ),
        migrations.CreateModel(
            name="RegistroPerdonazo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_concesion", models.DateTimeField(auto_now_add=True)),
                ("dias_extendidos", models.IntegerField()),
                ("motivo", models.TextField()),
                ("fecha_vencimiento_anterior", models.DateField()),
            ],
            options={
                "db_table": "contratos_registroperdonazo",
            },
        ),
        migrations.CreateModel(
            name="SLA",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "uptime_garantizado",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("tiempo_respuesta_horas", models.IntegerField()),
                ("detalles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "contratos_sla",
            },
        ),
    ]
