# Generated by Django 4.2.7 on 2026-07-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('RECURRENTE', 'Recurrente'), ('PERPETUO', 'Perpetuo'), ('PRO_BONO', 'Pro Bono')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('MORA', 'Mora'), ('GRACIA', 'Gracia'), ('SUSPENDIDO', 'Suspendido'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=30)),
                ('monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('dias_gracia_autorizados', models.IntegerField(default=0)),
                ('fin_periodo_gracia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratos_contrato',
            },
        ),
        migrations.CreateModel(
            name='RegistroPerdonazo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_concesion', models.DateTimeField(auto_now_add=True)),
                ('dias_extendidos', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_vencimiento_anterior', models.DateField()),
            ],
            options={
                'db_table': 'contratos_registroperdonazo',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('uptime_garantizado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_respuesta_horas', models.IntegerField()),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratos_sla',
            },
        ),
        migrations.AddConstraint(
            model_name='sla',
            constraint=models.CheckConstraint(check=models.Q(('uptime_garantizado__lte', 100.0)), name='chk_uptime_maximo'),
        ),
        migrations.AddField(
            model_name='registroperdonazo',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.RESTRICT, to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sla',
            field=models.ForeignKey(db_column='sla_id', on_delete=django.db.models.deletion.PROTECT, to='contratos.sla'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='software',
            field=models.ForeignKey(db_column='software_id', on_delete=django.db.models.deletion.PROTECT, to='catalogo.software'),
        ),
        migrations.AddConstraint(
            model_name='registroperdonazo',
            constraint=models.CheckConstraint(check=models.Q(('dias_extendidos__gt', 0)), name='chk_dias_extendidos_positivos'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'status'], name='idx_contrato_cliente_status'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['software', 'status'], name='idx_contrato_soft_status'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(check=models.Q(('fecha_vencimiento__gte', models.F('fecha_inicio')), ('fecha_vencimiento__isnull', True), _connector='OR'), name='chk_fecha_vencimiento_coherente'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(check=models.Q(('fin_periodo_gracia__gte', models.F('fecha_vencimiento')), ('fin_periodo_gracia__isnull', True), _connector='OR'), name='chk_periodo_gracia_coherente'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(check=models.Q(('dias_gracia_autorizados__gte', 0)), name='chk_dias_gracia_positivos'),
        ),
    ]
