# Generated by Django 4.2.7 on 2026-07-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('RECURRENTE', 'Recurrente'), ('PERPETUO', 'Perpetuo'), ('PRO_BONO', 'Pro Bono'), ('INTERNO', 'Interno / Propio')], max_length=30),
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos_proyectos/%Y/%m/%d/')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='contratos.contrato')),
            ],
            options={
                'db_table': 'contratos_archivoadjunto',
            },
        ),
    ]
