# Generated by Django 4.2.7 on 2026-07-09 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_initial"),
        ("clientes", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sla",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slas",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="registroperdonazo",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="obligacionslaauditlog",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligaciones_audit_logs",
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="obligacionslaauditlog",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="obligacionsla",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligaciones",
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="historialetapacontrato",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_etapas",
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="historialetapacontrato",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="cliente",
            field=models.ForeignKey(
                db_column="cliente_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="parent_contrato",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_contrato_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_hijas",
                to="contratos.contrato",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="sla",
            field=models.ForeignKey(
                db_column="sla_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="contratos.sla",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="software",
            field=models.ForeignKey(
                db_column="software_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.producto",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="archivoadjunto",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="contratos.contrato",
            ),
        ),
        migrations.AddConstraint(
            model_name="sla",
            constraint=models.CheckConstraint(
                check=models.Q(("uptime_garantizado__lte", 100.0)),
                name="chk_uptime_maximo",
            ),
        ),
        migrations.AddConstraint(
            model_name="sla",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nombre"), name="uniq_sla_nombre_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="registroperdonazo",
            constraint=models.CheckConstraint(
                check=models.Q(("dias_extendidos__gt", 0)),
                name="chk_dias_extendidos_positivos",
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["cliente", "status"], name="idx_contrato_cliente_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["software", "status"], name="idx_contrato_soft_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["tenant", "status"], name="idx_contrato_tenant_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fecha_vencimiento__gte", models.F("fecha_inicio")),
                    ("fecha_vencimiento__isnull", True),
                    _connector="OR",
                ),
                name="chk_fecha_vencimiento_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fin_periodo_gracia__gte", models.F("fecha_vencimiento")),
                    ("fin_periodo_gracia__isnull", True),
                    _connector="OR",
                ),
                name="chk_periodo_gracia_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                check=models.Q(("dias_gracia_autorizados__gte", 0)),
                name="chk_dias_gracia_positivos",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("frecuencia_facturacion__isnull", True),
                    ("tipo_contrato", "RECURRENTE"),
                    _connector="OR",
                ),
                name="chk_frecuencia_solo_recurrente",
            ),
        ),
    ]
