# Generated by Django 4.2.7 on 2026-07-04 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0002_alter_contrato_tipo_contrato_archivoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='etapa',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Draft)'), ('REVISION', 'En Revisión / Negociación'), ('APROBADO', 'Aprobado internamente'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('ACTIVO', 'Activo / Ejecutado'), ('ENMENDADO', 'Enmendado (Amended)'), ('TERMINADO', 'Terminado / Expirado')], default='BORRADOR', max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialEtapaContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etapa_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador (Draft)'), ('REVISION', 'En Revisión / Negociación'), ('APROBADO', 'Aprobado internamente'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('ACTIVO', 'Activo / Ejecutado'), ('ENMENDADO', 'Enmendado (Amended)'), ('TERMINADO', 'Terminado / Expirado')], max_length=30, null=True)),
                ('etapa_nueva', models.CharField(choices=[('BORRADOR', 'Borrador (Draft)'), ('REVISION', 'En Revisión / Negociación'), ('APROBADO', 'Aprobado internamente'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('ACTIVO', 'Activo / Ejecutado'), ('ENMENDADO', 'Enmendado (Amended)'), ('TERMINADO', 'Terminado / Expirado')], max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='contratos.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratos_historialetapa',
            },
        ),
    ]
