# Generated by Django 4.2.7 on 2026-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["tenant", "fecha_vencimiento"], name="idx_contrato_tenant_venc"
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["tenant", "etapa"], name="idx_contrato_tenant_etapa"
            ),
        ),
    ]
