# Generated by Django 4.2.7 on 2026-07-15 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contratos", "0003_contrato_idx_contrato_tenant_venc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="external_doc_id",
            field=models.CharField(
                blank=True,
                help_text="ID del documento en el procesador externo",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="external_editor",
            field=models.CharField(
                blank=True,
                choices=[("WORD", "Microsoft Word"), ("GDOCS", "Google Docs")],
                help_text="Procesador externo vinculado",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="external_last_sync",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de la última sincronización",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="external_lock_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiración del bloqueo para edición externa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="external_locked_by",
            field=models.ForeignKey(
                blank=True,
                db_column="external_locked_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_bloqueados_externamente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="external_sync_status",
            field=models.CharField(
                choices=[
                    ("NONE", "No vinculado"),
                    ("SYNCED", "Sincronizado"),
                    ("OUT_OF_SYNC", "Desactualizado"),
                    ("EDITING", "Editándose externamente"),
                ],
                default="NONE",
                help_text="Estado de la sincronización externa",
                max_length=20,
            ),
        ),
    ]
