# Generated by Django 4.2.7 on 2026-07-05 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0004_contrato_fecha_creacion_frecuencia_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='parent_contrato',
            field=models.ForeignKey(blank=True, db_column='parent_contrato_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_hijas', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.CreateModel(
            name='ObligacionSLAAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obligacion_id', models.IntegerField(blank=True, null=True)),
                ('tipo_obligacion', models.CharField(max_length=100)),
                ('actor_nombre', models.CharField(default='Sistema', max_length=150)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=10)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_audit_logs', to='contratos.contrato')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratos_obligacionsla_auditlog',
            },
        ),
        migrations.CreateModel(
            name='ObligacionSLA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_obligacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('penalizacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='contratos.contrato')),
            ],
            options={
                'db_table': 'contratos_obligacion_sla',
            },
        ),
    ]
