# Generated by Django 4.2.7 on 2026-07-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contratos",
            "0004_contrato_external_doc_id_contrato_external_editor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="firma_documento_firmado",
            field=models.FileField(
                blank=True,
                help_text="Documento final firmado y certificado",
                null=True,
                upload_to="contratos_firmados/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="firma_envelope_id",
            field=models.CharField(
                blank=True,
                help_text="ID del sobre de firma (DocuSign Envelope ID / Adobe Agreement ID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="firma_fecha_envio",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de envío para firma", null=True
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="firma_fecha_firma",
            field=models.DateTimeField(
                blank=True, help_text="Fecha en que se completó la firma", null=True
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="firma_proveedor",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin firmar"),
                    ("OTP", "Firma OTP Nativa"),
                    ("DOCUSIGN", "DocuSign"),
                    ("ADOBE", "Adobe Sign"),
                ],
                default="NONE",
                help_text="Proveedor de firma electrónica utilizado",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="firma_status",
            field=models.CharField(
                choices=[
                    ("NONE", "No enviado"),
                    ("PENDING", "Pendiente de firma"),
                    ("SIGNED", "Firmado"),
                    ("DECLINED", "Rechazado"),
                ],
                default="NONE",
                help_text="Estado del proceso de firma",
                max_length=20,
            ),
        ),
    ]
