# Generated by Django 4.2.7 on 2026-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0005_contrato_firma_documento_firmado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre personalizado del contrato",
                max_length=255,
                null=True,
            ),
        ),
    ]
