# Generated by Django 4.2.7 on 2026-07-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_producto_datos_adicionales_producto_tipo_licencia_and_more"),
        ("contratos", "0005_contrato_parent_contrato_contrato_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="software",
            field=models.ForeignKey(
                db_column="software_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.producto",
            ),
        ),
    ]
