# Generated by Django 4.2.7 on 2026-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0006_alter_contrato_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="texto_adicional_clausulas",
            field=models.TextField(
                blank=True,
                help_text="Texto editable para contratos generados por cláusulas",
                null=True,
            ),
        ),
    ]
