# Generated by Django 4.2.7 on 2026-07-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0006_contrato_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenFirmaContrato",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField()),
                ("fecha_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_confirmacion",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_firma",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "db_table": "contratos_tokenfirmacontrato",
                "indexes": [
                    models.Index(fields=["token"], name="idx_tokenfirma_token")
                ],
            },
        ),
    ]
