# Generated by Django 4.2.7 on 2026-07-18 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contratos", "0009_contrato_clausulas_actualizado_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="clausulas_estructuradas",
            field=models.JSONField(
                blank=True,
                help_text="Bloques del documento generado por cláusulas: lista de {titulo, texto, clausula_id?, version_id?, origen, modificada, nivel?, contenido?}. Tiene prioridad sobre texto_adicional_clausulas al renderizar.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ComentarioContrato",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contratos_comentario",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
