# Generated by Django 4.2.7 on 2026-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0010_alter_contrato_clausulas_estructuradas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentariocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SUGERENCIA", "Sugerencia"),
                    ("IMPORTANTE", "Importante"),
                    ("URGENTE", "Urgente"),
                ],
                default="SUGERENCIA",
                max_length=20,
            ),
        ),
    ]
