# Generated by Django 4.2.7 on 2026-07-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0011_comentariocontrato_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.CharField(
                choices=[
                    ("RECURRENTE", "Recurrente"),
                    ("PERPETUO", "Perpetuo"),
                    ("PRO_BONO", "Pro Bono"),
                    ("INTERNO", "Interno / Propio"),
                    ("REQUERIMIENTO", "Ficha de Requerimiento"),
                ],
                max_length=30,
            ),
        ),
    ]
