# Generated by Django 4.2.7 on 2026-07-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0013_alter_contrato_tipo_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentariocontrato",
            name="guest_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del invitado si el comentario se hace desde Guest Portal",
                max_length=150,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GuestLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("can_comment", models.BooleanField(default=True)),
                ("can_sign", models.BooleanField(default=False)),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_links",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "db_table": "contratos_guestlink",
                "indexes": [models.Index(fields=["token"], name="idx_guestlink_token")],
            },
        ),
    ]
