# Generated by Django 4.2.7 on 2026-07-20 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contratos", "0014_comentariocontrato_guest_name_guestlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="HitoContrato",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
                ("fecha_esperada", models.DateField()),
                ("fecha_completada", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "dias_aviso_previo",
                    models.IntegerField(
                        default=7,
                        help_text="Días de anticipación para notificar al responsable",
                    ),
                ),
                ("alerta_enviada", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hitos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contratos_hitocontrato",
                "ordering": ["fecha_esperada"],
            },
        ),
    ]
